Merged debian/* with 5.5.36 master

diff --git a/debian/mariadb-server-10.0.preinst b/debian/mariadb-server-10.0.preinst
--- a/debian/mariadb-server-10.0.preinst
+++ b/debian/mariadb-server-10.0.preinst
@@ -48,6 +48,20 @@ stop_server() {
 
 this_version=10.0
 
+# Show warning if old data exists
+if [ -d $DATADIR ]; then
+  db_input high mariadb-server/oneway_migration || true
+  db_go
+  db_get mariadb-server/oneway_migration || true
+  if [ "$RET" = "false" ]; then
+    echo "Aborting MariaDB installation." 1>&2
+    db_stop
+    exit 1
+  fi
+fi
+# Notice the uses of "|| true"  to  prevent  the  script  from  dying
+# For details see man page debconf-devel(7)
+
 # Abort if an NDB cluster is in use.
 if egrep -qi -r '^[^#]*ndb.connectstring|^[[:space:]]*\[[[:space:]]*ndb_mgmd' /etc/mysql/; then
   db_fset mysql-server/no_upgrade_when_using_ndb seen false || true
