Fix Lintian errors. Make template refrences explicit.

diff --git a/debian/mariadb-server-10.0.preinst b/debian/mariadb-server-10.0.preinst
--- a/debian/mariadb-server-10.0.preinst
+++ b/debian/mariadb-server-10.0.preinst
@@ -7,6 +7,8 @@
 #        * <old-preinst> abort-upgrade <new-version>
 #
 
+# TODO: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=526464
+
 . /usr/share/debconf/confmodule
 
 if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
@@ -46,8 +48,6 @@ stop_server() {
 
 ################################ main() ##########################
 
-this_version=10.0
-
 # Show warning if old data exists
 if [ -d $DATADIR ]; then
   db_input high mariadb-server/oneway_migration || true
@@ -78,22 +78,22 @@ fi
 show_downgrade_warning=0
 for i in `ls $DATADIR/debian-*.flag 2>/dev/null`; do
   found_version=`echo $i | sed 's/.*debian-\([0-9\.]\+\).flag/\1/'`
-  if dpkg --compare-versions "$this_version" '<<' "$found_version"; then
+  if dpkg --compare-versions "10.0" '<<' "$found_version"; then
     show_downgrade_warning=1
     break;
   fi
 done
 if [ "$show_downgrade_warning" = 1 ]; then
-  db_fset mariadb-server-$this_version/really_downgrade seen false || true
-  db_input medium mariadb-server-$this_version/really_downgrade || true
+  db_fset mariadb-server-10.0/really_downgrade seen false || true
+  db_input medium mariadb-server-10.0/really_downgrade || true
   db_go
-  db_get mariadb-server-$this_version/really_downgrade || true
+  db_get mariadb-server-10.0/really_downgrade || true
   if [ "$RET" = "true" ]; then
     rm -f $DATADIR/debian-*.flag
-    touch $DATADIR/debian-$this_version.flag
+    touch $DATADIR/debian-10.0.flag
   else
-    echo "Aborting downgrade from (at least) $found_version to $this_version." 1>&2
-    echo "If are sure you want to downgrade to $this_version, remove the file" 1>&2
+    echo "Aborting downgrade from (at least) $found_version to 10.0." 1>&2
+    echo "If are sure you want to downgrade to 10.0, remove the file" 1>&2
     echo "$DATADIR/debian-*.flag and try installing again." 1>&2
     db_stop
     exit 1
