Check if /var/lib/mysql exists before running 'find' on it
This fixes the following error:

find: ‘/var/lib/mysql’: No such file or directory
dpkg: error processing package mariadb-server-10.1 (--purge):
 subprocess installed post-removal script returned error exit status 1
Errors were encountered while processing:
 mariadb-server-10.1

diff --git a/debian/mariadb-server-10.1.postrm b/debian/mariadb-server-10.1.postrm
--- a/debian/mariadb-server-10.1.postrm
+++ b/debian/mariadb-server-10.1.postrm
@@ -60,13 +60,19 @@ if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; the
     # directory with file system data. See #829491 for details and
     # #608938 for potential mysql-server leftovers which erroneously
     # had been renamed.
-    find /var/lib/mysql -mindepth 1 \
-         -not -path '*/lost+found/*'     -not -name 'lost+found' \
-         -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
-         -delete
-    # "|| true" still needed as rmdir still exits with non-zero if
-    # /var/lib/mysql is a mount point
-    rmdir --ignore-fail-on-non-empty /var/lib/mysql || true
+    # Attempt removal only if the directory hasn't already been removed
+    # by dpkg to avoid failing on "No such file or directory" errors.
+    if [ -d /var/lib/mysql ]
+    then
+      find /var/lib/mysql -mindepth 1 \
+           -not -path '*/lost+found/*'     -not -name 'lost+found' \
+           -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
+           -delete
+
+      # "|| true" still needed as rmdir still exits with non-zero if
+      # /var/lib/mysql is a mount point
+      rmdir --ignore-fail-on-non-empty /var/lib/mysql || true
+    fi
     rm -rf /var/run/mysqld # this directory is created by the init script, don't leave behind
     userdel mysql || true
   fi
